"""Gated EWMA updates for entity behavioral profiles (ML pipeline Step 5b)."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Protocol

from anomaly_detection.common.models.entities import EntityProfile

from .config import DriftConfig


class ProfileStoreInterface(Protocol):
    """Minimal profile-store contract required by :class:`EWMAUpdater`."""

    def get_profile(self, entity_id: str) -> EntityProfile | None:
        """Return an entity profile when one has already been established."""

    def upsert_profile(self, profile: EntityProfile) -> None:
        """Persist a complete replacement profile."""


class EWMAUpdater:
    """Safely adapt warm entity baselines after low-risk inference events.

    The updater is deliberately dependency-injected.  It reads the current
    profile, creates a new version using the configured EWMA formula, and
    persists it only when the fused anomaly score is strictly below the gating
    threshold.  Scores at the threshold are rejected to protect against
    medium-risk Insider Drift being absorbed into the baseline.
    """

    def __init__(
        self, config: DriftConfig, profile_store: ProfileStoreInterface
    ) -> None:
        """Initialize the updater with validated policy and a profile store."""
        self.config = config
        self.profile_store = profile_store

    def should_update(self, anomaly_score: float) -> bool:
        """Return whether an anomaly score is safe to learn into a profile.

        Args:
            anomaly_score: The fused anomaly score generated by the pipeline.

        Raises:
            ValueError: If the score is outside the normalized ``[0, 1]`` range.
        """
        self._validate_anomaly_score(anomaly_score)
        return anomaly_score < self.config.gating_threshold

    def update(
        self,
        entity_id: str,
        anomaly_score: float,
        session_features: Sequence[float],
    ) -> EntityProfile | None:
        """Apply one gated EWMA update and return the persisted profile.

        ``None`` means no write occurred: either the event was gated as
        anomalous or there is no existing profile to adapt.  The latter keeps
        cold-start graduation exclusively in the cold-start handler.

        Args:
            entity_id: Entity whose established behavioral baseline is updated.
            anomaly_score: Fused score that gates profile adaptation.
            session_features: Normalized features from the current session.

        Raises:
            ValueError: If the score or feature-vector length is invalid.
        """
        if not self.should_update(anomaly_score):
            return None

        current_profile = self.profile_store.get_profile(entity_id)
        if current_profile is None:
            return None

        self._validate_feature_vector(session_features, current_profile)
        updated_baseline = self._compute_ewma(
            current_profile.baseline_vector,
            session_features,
        )
        updated_profile = current_profile.model_copy(
            update={
                "baseline_vector": updated_baseline,
                "last_updated": datetime.now(UTC).isoformat(),
                "profile_version": current_profile.profile_version + 1,
            }
        )
        self.profile_store.upsert_profile(updated_profile)
        return updated_profile

    def _compute_ewma(
        self,
        current_baseline: Sequence[float],
        session_features: Sequence[float],
    ) -> list[float]:
        """Compute ``(1 - alpha) * baseline + alpha * session_features``."""
        retained_weight = 1.0 - self.config.ewma_alpha
        return [
            retained_weight * current_value + self.config.ewma_alpha * session_value
            for current_value, session_value in zip(
                current_baseline, session_features, strict=True
            )
        ]

    @staticmethod
    def _validate_anomaly_score(anomaly_score: float) -> None:
        """Validate that a fused score conforms to its normalized contract."""
        if not 0.0 <= anomaly_score <= 1.0:
            raise ValueError("anomaly_score must be within [0.0, 1.0]")

    @staticmethod
    def _validate_feature_vector(
        session_features: Sequence[float], current_profile: EntityProfile
    ) -> None:
        """Ensure the incoming vector can be combined with the stored baseline."""
        if len(session_features) != len(current_profile.baseline_vector):
            raise ValueError(
                "session_features length must match the stored profile baseline length"
            )
