"""
Cold-Start Handler implementation (M10).
"""

from typing import Set, Tuple
import numpy as np
from datetime import datetime, timezone

from anomaly_detection.common.models.features import EntityFeatureVector
from anomaly_detection.common.models.ml_io import ProfilingOutput
from anomaly_detection.common.models.enums import EntityStatus, EntityType
from anomaly_detection.common.models.entities import EntityProfile

from src.profiling.profile_store import ProfileStore
from src.profiling.config import FEATURE_NAMES

from src.cold_start.config import ColdStartConfig
from src.cold_start.event_counter import EventCounter


class ColdStartHandler:
    """
    Standalone component that manages entities without sufficient history.
    Intercepts the ProfilingOutput, applies population-level confidence discounting,
    and manages graduation to personalized profiles.
    
    Resolution of Double-Discounting:
    M07 natively applies a penalty to its `anomaly_score` for cold-start entities. 
    This handler (M10) applies a discount specifically to the `confidence` field 
    of the BPM's `ProfilingOutput` (`discounted_confidence = raw_confidence * confidence_discount_factor`). 
    Because these adjustments apply to different fields (anomaly score vs. confidence), 
    there is no double-discounting of the same value.
    """

    def __init__(self, config: ColdStartConfig, store: ProfileStore) -> None:
        """
        Initialize the Cold-Start Handler.

        Args:
            config: Configuration parameters.
            store: M06 ProfileStore instance for profile lookup and graduation upsert.
        """
        self.config = config
        self.store = store
        self.counter = EventCounter(config.event_counter_persistence_path)
        self._warm_entities: Set[str] = set()

    def _determine_entity_type(self, entity_id: str) -> EntityType:
        """
        Derives the entity type from the entity ID prefix per DATA_SCHEMA.md.
        """
        if entity_id.startswith("usr_"):
            return EntityType.USER
        elif entity_id.startswith("svc_"):
            return EntityType.SERVICE_ACCOUNT
        elif entity_id.startswith("dev_"):
            return EntityType.EDGE_DEVICE
        
        # Fallback if unknown
        return EntityType.USER

    def handle(
        self, 
        entity_id: str, 
        feature_vector: EntityFeatureVector, 
        raw_profiling_output: ProfilingOutput
    ) -> ProfilingOutput:
        """
        Process the BPM's profiling output, track event counts, and graduate entities if ready.
        
        Args:
            entity_id: The ID of the entity.
            feature_vector: The current event's feature vector.
            raw_profiling_output: The ProfilingOutput generated by M06's BPM.
            
        Returns:
            The potentially modified ProfilingOutput.
        """
        # O(1) passthrough for warm entities
        if entity_id in self._warm_entities:
            return raw_profiling_output

        # Check the store directly. If it's there and has enough events, cache as warm.
        profile = self.store.get_profile(entity_id)
        if profile is not None and profile.event_count >= self.config.graduation_threshold:
            self._warm_entities.add(entity_id)
            return raw_profiling_output

        # The entity is in cold-start phase.
        self.counter.increment(entity_id, feature_vector.root)
        count = self.counter.get_count(entity_id)

        # Apply confidence discount
        raw_profiling_output.confidence = raw_profiling_output.confidence * self.config.confidence_discount_factor
        
        # We assume raw_profiling_output is actually an ExtendedProfilingOutput with entity_status 
        # and is_cold_start fields, or just a ProfilingOutput where we can set custom fields.
        # But per the prompt we must set entity_status and is_cold_start if they exist, or
        # dynamically attach them. In Python we can just set attributes if it's permitted, 
        # but since it's a Pydantic model we must ensure it's allowed.
        # M07 BPM already returns ExtendedProfilingOutput which has these fields.
        if hasattr(raw_profiling_output, "entity_status"):
            raw_profiling_output.entity_status = EntityStatus.COLD_START
        if hasattr(raw_profiling_output, "is_cold_start"):
            raw_profiling_output.is_cold_start = True
            
        # Set ambiguity reason per M10 spec (for EXPLAINABILITY.md / M09)
        # Note: M09 checks ambiguity_reason dynamically via getattr or directly if available
        setattr(
            raw_profiling_output, 
            "ambiguity_reason", 
            "New entity: no behavioral history available. Score reflects population-level baseline comparison."
        )

        # Check for graduation
        if count == self.config.graduation_threshold:
            # Graduate!
            vectors = np.array(self.counter.get_vectors(entity_id))
            
            mean_vec = np.mean(vectors, axis=0).tolist()
            std_vec = np.std(vectors, axis=0).tolist()
            # Prevent 0 variance
            std_vec = [max(s, 1e-4) for s in std_vec]
            
            entity_type = self._determine_entity_type(entity_id)
            now_str = datetime.now(timezone.utc).isoformat()
            
            new_profile = EntityProfile(
                entity_id=entity_id,
                entity_type=entity_type,
                baseline_vector=mean_vec,
                baseline_std=std_vec,
                sequence_history=[],  # Default empty, M06 manages this
                most_frequent_country="US",  # Placeholder
                known_mac_addresses=[],
                known_os_profiles=[],
                known_protocols=[],
                resource_access_counts={},
                command_frequency={},
                event_count=count,
                cold_start_flag=False,
                last_updated=now_str,
                profile_version=1
            )
            
            self.store.upsert_profile(new_profile)
            self._warm_entities.add(entity_id)
            self.counter.reset(entity_id)

        return raw_profiling_output
